apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: instana-eum-key
  namespace: robot-shop
spec:
  encryptedData:
    key: AgAvMXuSwlxSCT9K1reJjLtizr6xdAwwmLD7XayExYttQBZ/qdd6a+xaxoRdPHtzKTafPNRSlubFJPeIi7bAN7WGoKcQEksXFzqepyWKuTqlH80brSxAjPW3om/JRsFnIx2MeXc+QcF+DCY6Uq3DFjSYGtU25HI56fEm+UFBcW1YYVe4mtirY6zLQ8KoNeRUc5LODP19xhehO3kZ27MhyJ0JvQTvms4hPy0zpm1i3nR4ofVHguiibLrnWCszW2lMpIx8Q4dmDsI3pENclccUAknSJGHvcYNT2fInh98kJMovZeaGqIH86cqvLNrXoVBA2iWiuYR8vsBdDF0a+1vsXFx5/pjkulAmmrJbuDw/KY9p/C58x/DwHMVApefaN4/9KDQZZ2ZXcBJ4P4q0kTe9DthWDFohgmcRWGVdJQdR2t9S0S6KzwaXkcY8Y1UOHScgr7tVflP2AsFiW6oTDqR0VZHCB/IPDxBJRgkNuwYemqeduP/J4x2Cgje1CpueN/4kse6xqEMRXExjQUIHORDlHy+6EuwREH43IXSlymEGu3u3pAsOpQg8jcRP6GBSV0YlrFpxZrSaHzXh7USDlcWGkC3lmZtOb2GD2St3xvaJjbFZpSJ1e4YusI9zMI9IMTkO8j/mpinoZCoNDNSCpxxYL0gVcF/Tn/oB4N9fLq2wlq+uIvbXDAvhkzkRda4CQEhoKjNYEbQ3PetXMLKA2q50sNQjVOzs8pId
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: instana-eum-key
      namespace: robot-shop

